version: '3'
services:
  functiona:
    build:
      context: gcp-functionA/
      dockerfile: dockerfile.functiona
    ports:
      - "8081:8080"

  functionb:
    build:
      context: gcp-functionB/
      dockerfile: dockerfile.functionb
    ports:
      - "8080:8080"
