version: '3'
services:
  functionb:
    build:
      context: gcp-functionB/
      dockerfile: Dockerfile
    ports:
      - "8000:5433"
  functiona:
    build:
      context: gcp-functionA/
      dockerfile: Dockerfile
    ports:
      - "8001:5432"
    depends_on:
      - functionb
    links:
      - "functionb:fb"
