# Dockerfile for functionB
FROM python:3.8

COPY gcp_functionb /app/
RUN pip install Flask requests functions-framework

# Enable unbuffered mode for Python (better for debugging)
ENV PYTHONUNBUFFERED 1

# Expose the default Flask port
EXPOSE 8080

CMD ["functions-framework","--source=app/main.py", "--target=listen", "--debug"]


